# mkdocs.yml
site_name: "experimentalist_data"
site_author: L Ma
site_description: "experimentalist_data, utilities for experimantalist data"
site_url: "https://kausalflow.github.io/experimentalist-data"
repo_url: "https://github.com/kausalflow/experimentalist-data"
edit_uri: "blob/main/docs/"
repo_name: "kausalflow/experimentalist-data"


theme:
  name: "material"
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo/logo.png
  logo: assets/logo/logo_badge.svg



markdown_extensions:
  - admonition
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"
  - pymdownx.details


plugins:
  - autorefs
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: "sphinx"
      watch:
        - experimentalist_data


nav:
  - "Home": index.md
  - References:
    - "Introduction": references/index.md
    - "Excel":
      - "Excel Data": references/excel/excel_data.md
  - "Changelog": changelog.md
